### ISSUE TITLE
Gubbins 1.2.2 Crashing when adding to my Mod pack 

### ISSUE THREAD

**Issue by Issacozzman** [Lemonszz/gubbins#1]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 4/18/20 3:42 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/resource/ResourceReloadListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_2358.handler$zlo000$afterConstruct(class_2358.java:551)
	at net.minecraft.class_2358.<init>(class_2358.java:56)
	at net.minecraft.class_2246.<clinit>(class_2246.java:243)
	at net.minecraft.class_2378.method_10237(class_2378.java:85)
	at net.minecraft.class_2378$$Lambda$163/949314262.get(Unknown Source)
	at net.minecraft.class_2378.method_10238(class_2378.java:132)
	at net.minecraft.class_2378$$Lambda$204/632841653.accept(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
	at net.minecraft.class_2378.<clinit>(class_2378.java:131)
	at net.minecraft.class_2966.method_12851(class_2966.java:40)
	at net.minecraft.class_310.<init>(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.ClassNotFoundException: net.minecraft.resource.ResourceReloadListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 34 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_2358.handler$zlo000$afterConstruct(class_2358.java:551)
	at net.minecraft.class_2358.<init>(class_2358.java:56)
	at net.minecraft.class_2246.<clinit>(class_2246.java:243)
	at net.minecraft.class_2378.method_10237(class_2378.java:85)
	at net.minecraft.class_2378$$Lambda$163/949314262.get(Unknown Source)
	at net.minecraft.class_2378.method_10238(class_2378.java:132)
	at net.minecraft.class_2378$$Lambda$204/632841653.accept(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
	at net.minecraft.class_2378.<clinit>(class_2378.java:131)
	at net.minecraft.class_2966.method_12851(class_2966.java:40)
	at net.minecraft.class_310.<init>(class_310.java:395)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 20w16a
	Minecraft Version ID: 20w16a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 664135856 bytes (633 MB) / 805306368 bytes (768 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecsapi: Amecs API 1.0.0+20w11a
		appleskin: AppleSkin 1.0.8
		autoconfig1u: Auto Config v1 Updated 2.0.1
		blockus: Blockus 1.5.0
		blue_endless_jankson: jankson +
		bouncylife: Bouncy Life 1.1.7+mc20w16a
		campanion: Campanion 1.1.2+build.7
		cavebiomes: Cave Biomes 0.1.1
		chat-up: Chat Up! 1.0
		cloth: Cloth Events 2.0.2-unstable
		cloth-basic-math: Cloth Basic Math 0.4.1
		cloth-config2: Cloth Config v2 3.3.2-unstable
		diggusmaximus: Diggus Maximus 1.2.7-1.16
		durabilityviewer: Giselbaers Durability Viewer 1.16-20w10a-fabric0.5.1-1.7
		emerald_tools: Emerald Tools 1.0.6
		fabric: Fabric API 0.5.11+build.322-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c41
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.1+b7d52fa5ad
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea89ad
		fabric-commands-v0: Fabric Commands (v0) 0.1.4+a2a96bf9ad
		fabric-containers-v0: Fabric Containers (v0) 0.1.7+d249f7b6ad
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.5+88afe607ad
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825dad
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.3+a2a96bf9ad
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+04b9979441
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+1a47cd78ad
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.10+d249f7b6ad
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d6ad
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.6+2f56dff2ad
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+5b8a535a41
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d6ad
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7bad
		fabric-networking-v0: Fabric Networking (v0) 0.1.9+1a47cd7888
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.2.4+eb276f9cad
		fabric-particles-v1: fabric-particles-v1 0.1.2+12a8474cad
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.10+eb276f9cad
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.12+12a8474cad
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.28+c808269fad
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a60ad
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825dad
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.7+12a8474cad
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+53410490ad
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.1+1a47cd78ad
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.13+94c7834aad
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.3+9cd8d660ad
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba7ad
		fabricloader: Fabric Loader 0.8.2+build.194
		gameinfo: GameInfo 1.4.0a 20w14a
		gbfabrictools: GBfabrictools 1.2.0.20w10a
		gubbins: Gubbins beta-1.2.2-20w16a
		jankson: Jankson 2.0.1+j1.2.0
		justmap: Just Map 1.1.43
		kyrptconfig: Kytpt Config 1.0.0-1.16
		libcd: LibCapableData 2.3.1+20w15a
		lightoverlay: Light Overlay 5.0.2-unstable
		mcf-reap: MaxVar reap for fabric 1.2.1-16s
		minecraft: Minecraft 1.16-alpha.20.16.a
		modmenu: Mod Menu 1.10.2+build.1
		mousewheelie: Mouse Wheelie 1.4.5+mc20w14a
		mycommands: MyCommands Fabric 20w14a-01
		oldfishfarm: Old Fish Farm 1.0.0 20w14a
		orderly: Orderly 2.0.0-alpha.9-1.16
		org_jetbrains_annotations: annotations 18.0.0
		reborncore: Reborn Core 4.2.7+build.13
		roughlyenoughitems: Roughly Enough Items 4.1.8-unstable
		sandwichable: Sandwichable 1.0.2-snapshot
		simpledrawers: Simple Drawers 1.6.0-20w13b
		stuffz: StuffZ 2.0.1
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.3.9+build.17
		terraform: Terraform 1.6.1+build.8
		terrestria: Terrestria 1.3.3+build.7
		traverse: Traverse 2.2.2+build.5
		tweed: Tweed API 2.2.12
		vanilla-hammers: Vanilla Hammers 1.7.0
		waila: Hwyla 1.9.21
		water-erosion: Water Erosion 1.1.1
	Launched Version: fabric-loader-0.8.2+build.194-20w16a
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by Lemonszz** [comment]
Does the crash stop when you remove Gubbins? The crash report itself doesn't specifically point to it.

**Comment by Issacozzman** [comment]
Yes if I remove Gubbins Client will start up with it in it crashes with that Crash report

**Comment by Lemonszz** [comment]
Could you test this with Beta 1.2.3, it contains a crash fix with one of the mods you have installed (just map)

**Comment by Issacozzman** [comment]
Big thanks for fixing this so quick its working Now I have added it my Mod pack I'm putting out Thanks Again

Issac
